CREATE TABLE IF NOT EXISTS Users (
  id CHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Organizations (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT "",
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Permissions (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Categories (
  id CHAR(36) PRIMARY KEY,
  organization CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization) REFERENCES Organizations (id)
);

CREATE TABLE IF NOT EXISTS Products (
  id CHAR(36) PRIMARY KEY,
  category CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TINYTEXT NOT NULL,
  price DECIMAL(6,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category) REFERENCES Categories (id)
);

CREATE TABLE IF NOT EXISTS Warehouses (
  id CHAR(36) PRIMARY KEY,
  organization CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization) REFERENCES Organizations (id)
);

CREATE TABLE IF NOT EXISTS Stocks (
  id CHAR(36) PRIMARY KEY,
  warehouse CHAR(36) NOT NULL,
  product CHAR(36) NOT NULL,
  quantity INT NOT NULL,
  minimum_quantity INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (warehouse) REFERENCES Warehouses (id),
  FOREIGN KEY (product) REFERENCES Products (id),
  CHECK (quantity >= minimum_quantity AND minimum_quantity >= 0)
);
